apiVersion: v1
kind: Secret
metadata:
  name: vproapp-service
spec: 
  ports:
    - port: 80
      targetPort: vproapp-port
      protocol: TCP 
  selector: 
    app: vproapp    
  type: LoadBalancer

